#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: An Opensource Trading, Portfolio Management and Backoffice Platform

# Short bio or description (displayed in the header)
#description: Unify is a Trading Platform build by Traders and Fintech veterans. It's been designed and built from the ground up to be open and extendable.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://pbs.twimg.com/profile_images/824266621820747777/uxu-xhUL_400x400.jpg
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: GenoaIO/OpenUnify/
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: UnifyIO
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.genoa.io/unify

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#baseurl: "/GenoaIO/OpenUnify/"

redcarpet:
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
